[workspace]
members = [
    "binary/cli",
    "component/primitives",
    "component/consensus/gbft",
    "component/consensus/pow",
    "component/consensus/poa",
    "component/network",
    "component/runtime",
    "component/wasm"
]

[profile.release]
panic = "unwind"
keccak-hash = "0.4.0"
