[workspace]
members = [
    "binary/cli",
    "component/blockchain",
    "component/consensus/gbft",
    "component/consensus/pow",
    "component/consensus/poa",
    "component/network"
]

[profile.release]
panic = "unwind"